ZT_OPTS(3)
==========
:doctype: manpage

NAME
----
zt_opts - get and process arguments from command line

LIBRARY
-------
*zt_opts* library (libztopts, -lztopts)

SYNOPSIS
--------
#include <zt_opts.h>


#define ZT_OPT_NSO -1
#define ZT_OPT_NLO NULL
#define ZT_OPT_END() 0, NULL, NULL, NULL, NULL, NULL

typedef int (*zt_opt_error)(int code, char * fmt, ...);

typedef struct zt_opt_def zt_opt_def_t;

typedef int (*zt_opt_callback)(int argn, int defn, int * argc, char ** argv, zt_opt_def_t * def, zt_opt_error error);

struct zt_opt_def {
    char            sopt;
    char          * lopt;
    char          * arg;
    zt_opt_callback cb;
    void          * cb_data;
    char          * help;
};

typedef void (*zt_opt_validate)(zt_opt_def_t * args, zt_opt_error error);

int    zt_opt_null(int argn, int defn, int * argc, char ** argv, zt_opt_def_t * def, zt_opt_error error);

#ifdef HAVE_INTTYPES_H
int    zt_opt_intmax(int argn, int defn, int * argc, char ** argv, zt_opt_def_t * def, zt_opt_error error);
#endif /* HAVE_INTTYPES_H */

int    zt_opt_int(int argn, int defn, int * argc, char ** argv, zt_opt_def_t * def, zt_opt_error error);
int    zt_opt_long(int argn, int defn, int * argc, char ** argv, zt_opt_def_t * def, zt_opt_error error);
int    zt_opt_flag_int(int argn, int defn, int * argc, char ** argv, zt_opt_def_t * def, zt_opt_error error);
int    zt_opt_bool_int(int argn, int defn, int * argc, char ** argv, zt_opt_def_t * def, zt_opt_error error);
int    zt_opt_string(int argn, int defn, int * argc, char ** argv, zt_opt_def_t * def, zt_opt_error error);

int    zt_opt_help_stdout(int argn, int defn, int * argc, char ** argv, zt_opt_def_t * def, zt_opt_error error);
int    zt_opt_usage(const char * name, const char * help, zt_opt_def_t * opts);

char * zt_opt_get_value(int argn, int defn, char ** argv, zt_opt_def_t * def, int * args_consumed, zt_opt_error error);

void   zt_opt_validate_default(zt_opt_def_t * args, zt_opt_error error);

char * zt_opt_error_str(int code, char * fmt, ...);
char * zt_opt_verror_str(int code, char * fmt, va_list ap);
int    zt_opt_error_default(int code, char * fmt, ...);
int    zt_opt_verror_default(int code, char * fmt, va_list ap);

#define zt_opt_process(argc, argv, args) \
    zt_opt_process_args(argc, argv, args, NULL, NULL)

int    zt_opt_process_args(int * argc, char ** argv, zt_opt_def_t * args, zt_opt_validate validate, zt_opt_error error);


DESCRIPTION
-----------
zt_opts provides a declarative method to parse and act on command line arguments.

RETURN VALUES
-------------
*0*::
    success
*<0*::
    failure

EXAMPLES
--------
static int
local_opt_long(int argn, int defn, int * argc, char ** argv, zt_opt_def_t * def, zt_opt_error error) {
    long   result;
    char * end = NULL;
    int    args_consumed = 0;
    char * arg = zt_opt_get_value(argn, defn, argv, def, &args_consumed, error);

    errno  = 0;
    result = strtol(arg, &end, 0);

    if (errno) {
        /* check errno */
        error(errno, "invalid number '%s'", arg);
    }

    if (end && *end) {
        /* invalid character */
        error(EINVAL, "'%s' is not a number", arg);
    }

    if (def[defn].cb_data) {
        *(long *)def[defn].cb_data = result;
    }

    return args_consumed;
}

struct lfd {
    int data;
};

int
main(int argc, char ** argv) {
    int        bool_type        = 0;
    char     * str              = NULL;
    long       long_int         = 0;
    int        flag             = 0;
    int        flag2            = 0;
    struct lfd local_func_data  = {
        0
    };

    #define LONG_DESC "This is a really long string intended to overflow the wrap widths so that we can test how well they work.  This is only a test"
    struct zt_opt_def options[] = {
        { 'h',        "help",     NULL,           zt_opt_help_stdout,   "[options]",      "this help text"   },
        { 'b',        "bool",     "[true|false]", zt_opt_bool_int,      &bool_type,       "boolean test"     },
        { 's',        "string",   "text",         zt_opt_string,        &str,             LONG_DESC          },
        { 'f',        "func",     "arg",          local_func_with_args, &local_func_data, "generic function" },
        { 'l',        "long",     "int",          zt_opt_long,          &long_int,        "a long integer"   },
        { 'q',        ZT_OPT_NLO, NULL,           zt_opt_flag_int,      &flag,            "short only flag"  },
        { ZT_OPT_NSO, "quiet",    NULL,           zt_opt_flag_int,      &flag2,           "long only flag"   },
        { ZT_OPT_END() }
    };

    int               nargc = argc;
    char           ** pargv = argv;

    int               ret   = zt_opt_process_args(&nargc, pargv, options, NULL, NULL);
    if (ret < 0) {
        fprintf(stderr, "Error processing args");
        exit(1);
    }

    return 0;
}

DIAGNOSTICS
-----------
test


SEE ALSO
--------
test

BUGS
----
test

COPYING
-------
test
